# Generated by Django 4.1.6 on 2023-04-29 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_orderplaced_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
